name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    defaults:
      run:
        working-directory: ./django_drf_async
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: make test
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
